__package_name__ = "codesmith"
__description__ = "A software construction tool."
__url__ = "https://github.com/garym/codesmith"
__author__ = "Gary Martin"
__author_email__ = "gary.martin@physics.org"
__license__ = "Apache 2.0"
